### ISSUE TITLE
Out-ConsoleGridView doesn't handle ANSI escape sequences correctly

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/GraphicalTools#131]
It appears that gui.cs may not support rendering ANSI escape sequences.  In the meantime, if using pwsh 7.2+, `Out-ConsoleGridView` should use `StringDecorated` type to make sure all text is plain text.

https://twitter.com/Jaykul/status/1339064642715398150

**Comment by tig** [comment]
Tracking issue in gui.cs added: https://github.com/migueldeicaza/gui.cs/issues/1097

**Comment by migueldeicaza** [comment]
Why would gui.cs parse external escape sequences?

**Comment by tig** [comment]
Should be fixed by #141

**Comment by reaby** [comment]
> Why would gui.cs parse external escape sequences?

Well you wish to show colors from other sources, the ansi color sequences works kind of everywhere else, why not here!
But to say this is exact is my problem. I have written an ansiparser for a game color codes system. It translates the $rgb to ansi escapes and it works perfectly with Console.WriteLine but i can't get the output working at all with Terminal.Gui...

**Comment by tig** [comment]
This is not fixed.

I now understand the issue. Terminal.Gui is simply rendering the characters presented. Thus OCGV shows them.

Because powershell now colorized things in `gci` (e.g. directories), simple commands like `ls | ocgv` are useless:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/585482/171819696-d3fec054-cfe2-4c34-bf26-9e442e95b95f.png">

I am not sure what the right thing to do is. Is it expected that any Powershell function or cmdlet that takes piped input should look for and strip off ANSI escape sequences before displaying?

**Comment by tig** [comment]
Reading this: https://github.com/PowerShell/PowerShell/issues/13071

I'm looking for `StringDecorated` and/or `String.ToString(bool)`.

But since the cmdlet is currently built for PS 6.x, these aren't available?

Once I figure out how to access these, it should be trivial to fix this bug by changing the logic here to strip the ANSI from the input.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/585482/171827521-0eed4df6-107f-4888-9f70-a2b26fa980b0.png">

**Comment by tig** [comment]
Confimed fixed in the code currently in `master`:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/585482/182713218-91b3f7e7-5d9f-4b4e-8fb8-aa662d1fffea.png">

**Comment by SteveL-MSFT** [comment]
This fix should be in the release this month
