### ISSUE TITLE
Remove friendly bail out on Windows when upstream gui.cs issue is resolved

### ISSUE THREAD

**Issue by thoemmi** [PowerShell/GraphicalTools#52]
I have installed the ConsoleGuiTools module in PowerShell 7 on Windows 10 (Insider Preview, Slow Ring). However, when I call ` Get-Process | Out-ConsoleGridView`, I only get this error:
```
Out-ConsoleGridView: This cmdlet is not supported on this platform.
```

My `$PSVersionTable` says:
```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TylerLeonhardt** [comment]
The [blog post](https://devblogs.microsoft.com/powershell/introducing-consoleguitools-preview/) said that this module doesn't work on Windows yet due to a [gui.cs issue](https://github.com/migueldeicaza/gui.cs/issues/339).

I'm going to rename this issue to track the removing of the logic I added to ConsoleGuiTools to make the error message nicer.

**Comment by thoemmi** [comment]
Er, my bad. Sorry, haven't read the current limitations properly. Didn't expect that Windows isn't first class citizen :wink:

**Comment by TylerLeonhardt** [comment]
Is usually is! But in this case there was nothing I can do short of digging into gui.cs' codebase.

**Comment by TylerLeonhardt** [comment]
Released :)
