### ISSUE TITLE
Request: Control over how columns are collapsed/truncated

### ISSUE THREAD

**Issue by LarsFosdal** [PowerShell/GraphicalTools#73]
Example:
The two last columns contain long paths that typically only differ at the end.

![image](https://user-images.githubusercontent.com/7009177/77149960-0c75b980-6a93-11ea-944d-a54eabefa8cc.png)

It would be nice if you could select if columns should be collapsed/truncated from left or right and at a fixed length.
`Get-SourceData | Select-Object FactoryNo, LocationName, StagingPath, CentralUpgradeOverrideDir | Out-ConsoleGridUI -passthru -ColumnWidth 3, 20, -20, -30
`
Reserving 3 and 20 chars for the first and second column, and 20 and 30 chars for the third and fourth column with the - sign indicating that the truncation should be on the left side.

Alternatively, offer a parameter with strings that the display would collapse:
`Get-SourceData | Select-Object FactoryNo, LocationName, StagingPath, CentralUpgradeOverrideDir | Out-ConsoleGridUI -passthru -collapse "\\app100213\Staging", "\\tine.no\applikasjon\TINE_WMS"
`

Note that only the display should collapse/truncate while the actual values should be passed on in their original length.

**Comment by iSazonov** [comment]
Best way to have a scrolling in column but it is difficult to implement.

**Comment by mossrich** [comment]
Some other options to consider: 
1) Eliminate some cruft columns: do you really need 3 columns for the checkbox? It's ok to have a √ character next to an item to indicate it's selected. 
2) Show [ellipses](http://html-codes.info/ansi/html/ANSI-horizontal%20ellipsis_133) … at the end of a value that has been truncated.  Some terminals may not support the single-character ellipses, and using three dots would probably exacerbate the truncation problem. For these cases a single dot could indicate truncation. 
3) Choose a different algorithm for determining max column width to eliminate truncation. Check all the visible values' length instead of half of them.  It can be visually jarring to have columns resize when you scroll, but it's a simpler implementation than many others. 
4) Allow horizontal scroll when the width is wider than the visible portal. It's not ideal, but it works like Out-GridView. 

I considered vertical scrolling when I wrote [AsciiMenu.ps1](https://github.com/mossrich/PowershellRecipes/blob/master/AsciiMenu.ps1).  The scroll thumb algorithm was difficult to write and might be reusable. Feel free to use that code if it suits your purpose.

**Comment by tig** [comment]
@andschwa This should be closed as won't fix since it's for the Avalona version.
